# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER ALT, F12, Email, exec, /home/theonlyvoivod/.config/hypr/scripts/paste-email.sh

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
unbind = SUPER, W
unbind = SUPER, K
unbind = SUPER, H
unbind = SUPER, L
unbind = SUPER, J
unbind = SUPER ALT, SPACE
unbind = SUPER, mouse:273
unbind = SUPER, MOUSE_DOWN
unbind = SUPER, MOUSE_UP
unbind = SUPER, F
unbind = SUPER ALT, F
unbind = SUPER SHIFT, F


bindd = SUPER, Q, Close window, killactive,
bindd = SUPER SHIFT, K, Show key bindings, exec, omarchy-menu-keybindings

bindd = SUPER, H, Focus on left window, movefocus, l
bindd = SUPER, L, Focus on right window, movefocus, r
bindd = SUPER, K, Focus on above window, movefocus, u
bindd = SUPER, J, Focus on below window, movefocus, d

bindd = SUPER SHIFT, SPACE, Omarchy menu, exec, omarchy-menu

# Move/resize windows with mainMod + LMB/RMB and dragging
bindmd = SUPER, mouse:272, Move window, movewindow
bindmd = SUPER ALT, mouse:272, Resize window, resizewindow

bindd = SUPER SHIFT, S, Full screen, fullscreen, 0


# gesture = 2, pinch, cursorZoom, 3, live

gesture = 4, down, cursorZoom, 1, multi
gesture = 4, up, cursorZoom, 2, multi
