input {
  kb_layout = us,ua
  kb_options = compose:caps, grp:alt_space_toggle

  repeat_rate = 30
  repeat_delay = 240

  numlock_by_default = true

  sensitivity = 0.3

  accel_profile = adaptive

  touchpad {
    clickfinger_behavior = true

    scroll_factor = 0.7

    drag_3fg = 1
  }

}

device {
    name = tpps/2-ibm-trackpoint
    sensitivity = 0.5
    accel_profile = flat
}

  cursor {
    zoom_rigid = true
    zoom_detached_camera = false
  }


windowrule = match:class (Alacritty|kitty|foot), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2
