[mgr]
show_hidden = true
linemode = "size"
sort_by = "natural"


[opener]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]

open = [
    # Image files
    { run = 'swayimg "$@"', desc = "Open with Swayimg", for = "linux", mime = "image/*" },

    # Zip/Rar
    { run = 'unzip -j "$@"', desc = "Unzip", for = "linux", mime = "application/zip" },
    { run = 'unrar e -j "$@"', desc = "Unrar", for = "linux", mime = "application/rar" },

    # Fallback for other file types
    { run = 'xdg-open "$@"', desc = "Open with default application", for = "linux" },
]

play = [
    # Sound files
    { run = 'mpv "$@"', orphan = true, desc = "Play with MPV", for = "linux", mime = "audio/oga" },

    # Videos 
    { run = 'mpv --force-window "$@"', orphan = true, desc = "Play with MPV", for = "linux", mime = "video/*" },

]

[preview]
max_width = 2000
max_height = 2000
tab_size = 4
