# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Decorations Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

general {
    gaps_in = 8
    gaps_out = 8 
    border_size = 2
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
    col.active_border = rgb(fabd2f)
}

decoration {
    rounding = 4
    rounding_power = 1
    active_opacity = 1.0
    dim_inactive = false 

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 1
        passes = 3
        vibrancy = 0.4
    }
}

