# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

input {
    kb_layout = us,ua
    kb_model =
    kb_options = grp:alt_space_toggle
    kb_rules = 
    repeat_rate = 20
    repeat_delay = 150
    follow_mouse = 1
    sensitivity = 0.3
    accel_profile = "flat"
    emulate_discrete_scroll = 2

    touchpad {
        natural_scroll = false
        disable_while_typing = true
        middle_button_emulation = true
        drag_lock = 1
        clickfinger_behavior = true
        drag_3fg = 1
        tap-to-click = true
        tap-and-drag = true
        scroll_factor = 1.4
        tap_button_map = "lmr"
    }
}
