# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Keybinds                            ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

$mainMod = SUPER
$terminal = kitty 
$fileManager = nemo
$menu = rofi -show drun
$clipboard_history = cliphist list | rofi -dmenu | cliphist decode | wl-copy

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, C, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod, P, pseudo,
bind = $mainMod SHIFT, M, exec, hyprctl dispatch exit
bind = $mainMod, F, fullscreen

bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

bind = , xf86audioraisevolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = , xf86audiolowervolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = , XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
bind = , XF86MonBrightnessUp, exec, brightnessctl set +10%
bind = , XF86MonBrightnessDown, exec, brightnessctl set 10%-

bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

# Restart waybar
# bind = $mainMod SHIFT, R, exec, pkill waybar && hyprctl dispatch exec waybar

bind = ,PRINT, exec, hyprshot -m region --clipboard-only
bind = $mainMod, PRINT, exec, hyprshot -m output --clipboard-only
bind = $mainMod SHIFT, T, exec, pkill swaync && swaync && notify-send 'Dummy notify'

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, Control_L, movewindow
bindm = $mainMod, mouse:273, resizewindow
bindm = $mainMod, ALT_L, resizewindow

binde = $mainMod SHIFT, l, resizeactive, 10 0
binde = $mainMod SHIFT, h, resizeactive, -10 0
binde = $mainMod SHIFT, k, resizeactive, 0 -10
binde = $mainMod SHIFT, j, resizeactive, 0 10

binde = $mainMod ALT, l, movewindow, r
binde = $mainMod ALT, h, movewindow, l


bind = $mainMod, T, exec, ~/.config/rofi/scripts/todofi.sh

bind = $mainMod ALT, D, exec, ~/.config/hypr/scripts/launch_dev_layout.sh


# gesture = 4, horizontal, workspace
gesture = 3, pinchin, fullscreen
gesture = 3, pinchout, float

bind = $mainMod SHIFT, W, exec, ~/.config/hypr/scripts/wallpaper_switch.sh

bind = $mainMod SHIFT, R, exec, killall waybar || waybar

bind = $mainMod ALT, N, exec, ~/.config/rofi/scripts/rofi-wifi-menu.sh
bind = $mainMod ALT, M, exec, rofi-bluetooth

gesture = 2, left, dispatcher, exec, wtype -M alt h -m alt
gesture = 2, right, dispatcher, exec, wtype -M alt l -m alt 

