# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Windowrules Configuration                ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Windows Rules https://wiki.hyprland.org/Configuring/Window-Rules/ #

# Float Necessary Windows
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol)
windowrule = float on, match:class ^()$, match:title ^(Picture in picture)$
windowrule = float on, match:class ^()$, match:title ^(Save File)$
windowrule = float on, match:class ^()$, match:title ^(Open File)$
windowrule = float on, match:class ^(LibreWolf)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$
windowrule = float on, match:class ^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$
windowrule = float on, match:class ^(CachyOSHello)$
windowrule = float on, match:class ^(zenity)$
windowrule = float on, match:class ^()$, match:title ^(Steam - Self Updater)$
# Increase the opacity
windowrule = opacity 0.92, match:class ^(thunar|nemo)$
windowrule = opacity 0.96, match:class ^(discord|armcord|webcord)$
windowrule = opacity 0.95, match:title ^(QQ|Telegram)$
windowrule = opacity 0.95, match:title ^(NetEase Cloud Music Gtk4)$
# General window rules
windowrule = float on, size 960 540, move ((monitor_w*0.25)-), match:title ^(Picture-in-Picture)$
windowrule = float on, move ((monitor_w*0.25)-), size 960 540, match:title ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
windowrule = pin on, match:title ^(danmufloat)$
windowrule = rounding 5, match:title ^(danmufloat|termfloat)$
windowrule = opacity 1.0, animation slide right, match:class ^(kitty|Alacritty)$
windowrule = no_blur on, match:class ^(org.mozilla.firefox)$
# Windows Rules End #

# Workspaces Rules https://wiki.hyprland.org/Configuring/Workspace-Rules/ #
# workspace = 1, default:true, monitor:$priMon
# workspace = 6, default:true, monitor:$secMon
# Workspace selectors https://wiki.hyprland.org/Configuring/Workspace-Rules/#workspace-selectors
# workspace = r[1-5], monitor:$priMon
# workspace = r[6-10], monitor:$secMon
# workspace = special:scratchpad, on-created-empty:$applauncher
# no_gaps_when_only deprecated instead workspaces rules with selectors can do the same
# Smart gaps from 0.45.0 https://wiki.hyprland.org/Configuring/Workspace-Rules/#smart-gaps
workspace = w[tv1-10], gapsout:5, gapsin:3
workspace = f[1], gapsout:5, gapsin:3
# Workspaces Rules End #

# Layers Rules #
layerrule = animation slide, match:namespace namespace:logout_dialog
# layerrulev2 = animation popin, namespace:waybar
layerrule = animation slide, match:namespace namespace:waybar
layerrule = animation fade, match:namespace namespace:wallpaper
# Layers Rules End #

workspace = w[tv1], gapsout:4, gapsin:8 
workspace = f[1], gapsout:0, gapsin:0

windowrule = border_color rgba(141517FF),match:workspace w[tv1]
windowrule = border_size 1,match:workspace w[tv1]


windowrule = float on, match:class ^(mpv)$

